spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        password: ${TAMK_DB_PASS}
        username: ${TAMK_DB_USER}
        url: 'jdbc:postgresql://${TAMK_DB_HOST}/${TAMK_DB_NAME}'
    flyway:
        locations: classpath:db-migration
        default-schema: 'tamk'