spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        password: admin
        username: stefan
        url: 'jdbc:postgresql://localhost:5432/tamk'
    flyway:
        locations: classpath:db-migration
        default-schema: 'tamk'